spring:
  datasource:
    url: jdbc:h2:mem:releasemanagerDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_schema: MANAGER
  sql:
    init:
      mode: always